# Generated by Django 3.0.3 on 2020-04-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('howtogo', models.CharField(max_length=20)),
                ('quiz1', models.CharField(max_length=50)),
                ('quiz2', models.CharField(max_length=50)),
                ('quiz3', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['museum_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('student_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feeling', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=13)),
                ('museum_number', models.CharField(max_length=13)),
                ('auth', models.CharField(max_length=1)),
                ('quiz1_answer', models.CharField(max_length=50)),
                ('quiz2_answer', models.CharField(max_length=50)),
                ('quiz3_answer', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['student_number'],
            },
        ),
    ]
