# Generated by Django 2.2.12 on 2020-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
