# Generated by Django 2.2.12 on 2020-05-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0002_watch_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watch_student',
        ),
    ]
