# Generated by Django 3.0.3 on 2020-05-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0002_auto_20200505_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Museum.Museum'),
        ),
    ]
