# Generated by Django 3.0.3 on 2020-05-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0003_auto_20200505_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='user',
            new_name='project',
        ),
    ]
