# Generated by Django 2.2.12 on 2020-05-17 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Museum', '0004_number_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompleteStatue', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='number_watch',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'ordering': ['modify_date']},
        ),
        migrations.RemoveField(
            model_name='watch',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='museum_number',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='student_number',
        ),
        migrations.AddField(
            model_name='watch',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Museum.Museum'),
        ),
        migrations.AddField(
            model_name='watch',
            name='stampStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='quiz1_answer',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='watch',
            name='quiz2_answer',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='watch',
            name='quiz3_answer',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='watch',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Museum.StudentProject'),
        ),
    ]
