# Generated by Django 3.0.3 on 2020-05-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0005_auto_20200517_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Total',
                'managed': False,
            },
        ),
    ]
