# Generated by Django 3.0.3 on 2020-05-26 05:43

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0006_total'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration('select * from Museum_Watch', 'Total'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(None, 'Total'),
        ),
    ]
