# Generated by Django 3.0.3 on 2020-05-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum', '0007_auto_20200526_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproject',
            old_name='CompleteStatue',
            new_name='CompleteState',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='create_date',
        ),
        migrations.AddField(
            model_name='watch',
            name='create_Stamp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='create_Stamp_time',
            field=models.TimeField(null=True),
        ),
    ]
